create table member (
                        id bigint generated by default as identity,
                        user_id varchar(15),
                        password varchar(20),
                        user_name varchar(20),
                        email varchar(100),
                        grade varchar(10) default 'MEMBER' check (grade in ('ADMIN', 'MEMBER', 'BLOCKED')) ,
                        primary key (id)
);